version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gonewsdesk
    main: .
    binary: gonewsdesk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - src: config.yaml
        dst: config.example.yaml

checksum:
  name_template: checksums.txt

changelog:
  use: github
