# Each source can be toggled independently. At least one enabled source is required.
stocklabs:
  enabled: true # toggle to enable/disable the stocklabs source
  includeHistorical: true # toggle to fetch historical news in the stream when the app starts

alpaca:
  enabled: false # toggle to enable/disable the alpaca source
  # recommended to use a paper account credentials here, for the least privilege principle.
  apiKeyID: "" # alpaca API key ID
  apiKeySecret: "" # alpaca API key secret

filter:
  # keywords to exclude from the news stream.
  # if any of these keywords are found in the news headline, the news will be excluded.
  # case-insensitive substring match.
  excludeKeywords: []
    # - "canada"
    # - "china"
    # - "russia"
  # keywords to include in the news stream.
  # if set, only news items that contain at least one of these keywords in the headline will be included.
  # case-insensitive substring match.
  includeKeywords: []
    # - "iran"
    # - "hormuz"
    # - "trump"
  # keywords to highlight in the news stream.
  # if set, and news items that contain at least one of these keywords in the headline, the news tile will be highlighted.
  # case-insensitive substring match.
  highlightKeywords: []
    # - "strike"
    # - "ceasefire"

debug: false # toggle to enable/disable printing debug logs to the log inspector panel
