# Each source can be toggled independently. At least one enabled source is required.
stocklabs:
  enabled: true

alpaca:
  enabled: false
  apiKeyID: ""
  apiKeySecret: ""

filter:
  # keywords to exclude from the news stream.
  # if any of these keywords are found in the news headline, the news will be excluded.
  # case-insensitive substring match.
  excludeKeywords: []
    # - "test"
    # - "demo"
    # - "example"
  # keywords to include in the news stream.
  # if set, only news items that contain at least one of these keywords in the headline will be included.
  # case-insensitive substring match.
  includeKeywords: []
    # - "stock"
    # - "market"
    # - "economy"
  # keywords to highlight in the news stream.
  # if set, and news items that contain at least one of these keywords in the headline, the news tile will be highlighted.
  # case-insensitive substring match.
  highlightKeywords: []
    # - "stock"
    # - "market"
    # - "economy"
